### ISSUE TITLE
pkill not found

### ISSUE THREAD

**Issue by kosielemmer** [lokiagent/K1-Backup#3]
Hi

When I run the backup from the helper menu I get a pkill not found error and have to break out of the script

Fll text
/usr/data/helper-script/files/git-backup/git-backup.sh: line 304: pkill: not found

Thanks

**Comment by lokiagent** [comment]
I noticed that as well on a fresh install recently. If you log out of the shell and log back in, it works correctly.

**Comment by kosielemmer** [comment]
Confirmed - that works - thanks
